spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  data:
    mongodb:
      host: mongobd.tacocloud.com
      port: 27017
      username: tacocloud
      password: s3cr3tP455W0rd
      database: tacoclouddb